os: linux
dist: xenial
language: node_js
node_js:
  - 10
  - 12
  - 14

notifications:
  email: false
env:
  global:
  - secure: "fsW/dvC3qp3tSEKjmFgJJkt3rw3zMmmFj1QNIx6ZTMvzWN7X+NDb3BSFpFSzM5YoJB3RuVxhTCnIekuf3Ekh4ykQ6amWs2Es/EFdS++d1xwnir2EseocpmfTs32GD47obVnUmkbS0qMCZkTHU12PGrD8HOD46PKtBnMQ94Z8kOY="
  - secure: "aPsjc1RrkRL8C7G9KX2XtwgHRXTQI3lXzUh6xTZRMCPrLXyDvEw+qFgZc/yyXTDwk1h+hop47njFpw2j6SNNR59ZjNHLocmq4ULr+GX6qjLmIwwUnfjDXnF/T9idhTk1G9zIOSP+Fl0mN2Oj2szqoJgoKY9jWQrZxpO7pnSj+2s="
after_failure:
- "./travis.sh revert"
after_success:
- "./travis.sh merge"
